version: '3.8'

services:
  manticore_faucet:
    build: .
    container_name: manticore_faucet_service
    restart: unless-stopped
    environment:
      - FLASK_ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379  # Set the internal Redis port to 6379
      - NODE_HOST=192.168.1.211
      - NODE_PORT=8819
    volumes:
      - .:/app
    depends_on:
      - redis
    ports:
      - "5000:5000"

  redis:
    image: "redis:latest"
    container_name: redis_service
    restart: unless-stopped
    ports:
      - "6370:6379"  # Map external port 6370 to internal Redis port 6379
